"use client";

import { Fragment, useCallback, useEffect, useMemo, useState } from "react";
import clsx from "clsx";
import PropTypes from "prop-types";
import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import SectionHeader from "./SectionHeader";
import ArrowButton from "./ArrowButton";
import ResearchPaperCarousel from "./ResearchPaperCarousel";

export default function TopicOverview({ summary, totalPapers, topics, curationStats, diversityMetrics }) {
  const topicEntries = useMemo(() => {
    return Object.entries(topics || {}).sort((a, b) => (b[1].paper_count || 0) - (a[1].paper_count || 0));
  }, [topics]);
  const totalTopics = topicEntries.length;
  const [activeIndex, setActiveIndex] = useState(0);
  const activeEntry = topicEntries[activeIndex] || topicEntries[0];
  const activeKey = activeEntry?.[0];
  const activeTopic = activeEntry?.[1];
  const activePapers = activeTopic?.top_papers || activeTopic?.topPapers || [];

  const shouldReduceMotion = useReducedMotion();

  // Format methodology text - totalPapers is interpolated into prose
  const methodologyText = `This newsletter is generated by an AI pipeline that processes the metadata and abstracts of every new arXiv HCI paper from the past week—${totalPapers} this issue. Each paper is scored on three dimensions: Practice (applicability for practitioners), Research (scientific contribution), and Strategy (industry implications), with scores from 1-5. Papers passing threshold are grouped into topic clusters, and each cluster is summarized to capture what that body of research is exploring.`;

  // Format selection criteria text (second paragraph)
  const selectionText = `The pipeline builds a curated selection that balances high scores with topic diversity—and deliberately includes at least one 'contrarian' paper that challenges prevailing assumptions. This selection is then analyzed to identify key findings (patterns across multiple papers) and surprises (results that contradict conventional wisdom). A narrative synthesis ties the week's research together under a unifying frame.`;



  const goTo = useCallback((index) => {
    setActiveIndex(index);
  }, []);

  const handleNext = useCallback(() => {
    if (totalTopics <= 1) return;
    setActiveIndex((prev) => (prev + 1) % totalTopics);
  }, [totalTopics]);

  const handlePrev = useCallback(() => {
    if (totalTopics <= 1) return;
    setActiveIndex((prev) => (prev - 1 + totalTopics) % totalTopics);
  }, [totalTopics]);

  const handleKeyNavigation = useCallback(
    (event) => {
      if (event.key === "ArrowRight" || event.key === "ArrowDown") {
        event.preventDefault();
        handleNext();
      } else if (event.key === "ArrowLeft" || event.key === "ArrowUp") {
        event.preventDefault();
        handlePrev();
      }
    },
    [handleNext, handlePrev]
  );

  if (!activeTopic) return null;



  const containerVariants = {
    enter: {
      transition: {
        staggerChildren: 0.1,
      },
    },
    exit: {
      transition: {
        staggerChildren: 0.05,
      },
    },
  };

  const itemVariants = {
    initial: {
      y: 15,
      opacity: 0,
    },
    enter: {
      y: 0,
      opacity: 1,
      transition: {
        type: "spring",
        stiffness: 300,
        damping: 30,
      },
    },
    exit: {
      y: -10,
      opacity: 0,
      transition: {
        duration: 0.2,
      },
    },
  };

  return (
    <section id="topic-overview" className="max-w-content mx-auto px-4 lg:px-0">
      <div className="bg-base-100/50 dark:bg-base-900/30 border border-base-200 dark:border-base-800 rounded-2xl p-8 md:p-12 space-y-12">
        {/* Transparency & Methodology Header */}
        <div className="space-y-6">
          <div className="space-y-4">
            <SectionHeader label="ABOUT THIS ISSUE" className="text-emerald-600 dark:text-emerald-400" />
            <h2 className="font-altDisplay text-3xl md:text-4xl font-bold text-hci-primary dark:text-flexoki-base-50">
              How this newsletter was synthesized?
            </h2>
          </div>

          <div className="grid md:grid-cols-2 gap-8 pt-6 border-t border-base-200 dark:border-base-800">
            <div className="space-y-4">
              <h4 className="font-altSans text-xs uppercase tracking-widest text-flexoki-base-500">Methodology</h4>
              <p className="font-altSans text-body-md leading-relaxed font-light text-hci-secondary dark:text-flexoki-base-300">
                {methodologyText}
              </p>
            </div>
            <div className="space-y-4">
              <h4 className="font-altSans text-xs uppercase tracking-widest text-flexoki-base-500">Selection Criteria</h4>
              <p className="font-altSans text-body-md leading-relaxed font-light text-hci-secondary dark:text-flexoki-base-300">
                {selectionText}
              </p>
            </div>
          </div>
        </div>

        {/* Key Themes Discovery */}
        <div className="space-y-8">
          <div className="flex items-center justify-between">
            <h4 className="font-altSans text-xs uppercase tracking-widest text-flexoki-base-500">
              Key Themes Discovered
            </h4>
            <div className="hidden md:flex items-center gap-2">
              <ArrowButton
                direction="left"
                onClick={handlePrev}
                disabled={totalTopics <= 1}
              />
              <ArrowButton
                direction="right"
                onClick={handleNext}
                disabled={totalTopics <= 1}
              />
            </div>
          </div>

          <div className="flex flex-wrap gap-3">
            {topicEntries.map(([key, topic], index) => {
              const isActive = index === activeIndex;
              return (
                <button
                  key={`${topic.headline}-${index}`}
                  onClick={(e) => {
                    e.preventDefault();
                    goTo(index);
                  }}
                  className={clsx(
                    "group flex items-center gap-2 rounded-full border px-3 py-1.5 font-altSans text-body-sm leading-tight transition-all duration-200 shadow-sm",
                    isActive
                      ? "border-base-900 bg-base-900 text-base-50 dark:border-base-100 dark:bg-base-100 dark:text-base-900 shadow-lg"
                      : "border-base-200 bg-white/50 text-hci-secondary hover:border-base-400 hover:bg-base-100/80 hover:text-base-900 dark:border-base-800 dark:bg-base-900/40 dark:text-flexoki-base-400 dark:hover:border-base-600 dark:hover:bg-base-800 dark:hover:text-flexoki-base-100"
                  )}
                >
                  <span className="font-medium">#{key}</span>
                  <span
                    className={clsx(
                      "flex h-5 w-5 items-center justify-center rounded-full text-[10px] font-bold leading-none",
                      isActive
                        ? "bg-base-50/20 text-current dark:bg-base-900/10"
                        : "bg-base-100 text-base-500 group-hover:bg-base-200 group-hover:text-base-900 dark:bg-base-800 dark:text-flexoki-base-500 dark:group-hover:bg-base-700 dark:group-hover:text-flexoki-base-200"
                    )}
                  >
                    {topic.paper_count}
                  </span>
                </button>
              );
            })}
          </div>

          <div
            className="relative pt-4"
            role="region"
            aria-label="Topic overview carousel"
            tabIndex={0}
            onKeyDown={handleKeyNavigation}
          >
            <AnimatePresence initial={false} mode="wait">
              <motion.article
                key={activeIndex}
                variants={containerVariants}
                initial="initial"
                animate="enter"
                exit="exit"
                className="grid gap-12 lg:grid-cols-[1fr_1.5fr] items-start"
              >
                <motion.div className="space-y-6" variants={itemVariants}>
                  <div className="space-y-4">
                    <h4 className="font-altSans text-xs uppercase tracking-widest text-flexoki-base-500">
                      Field Report: {activeKey}
                    </h4>
                    <h3 className="font-altSans text-2xl text-hci-primary dark:text-flexoki-base-50 leading-tight">
                      {activeTopic.headline}
                    </h3>
                    <p className="font-altSans text-body-md leading-relaxed font-light text-hci-secondary dark:text-flexoki-base-300">
                      {activeTopic.field_report || activeTopic.fieldReport}
                    </p>
                    <span className="type-label !font-medium opacity-80">
                      {activeIndex + 1}/{totalTopics}
                    </span>
                  </div>
                </motion.div>

                <motion.div variants={itemVariants} className="min-w-0 space-y-4">
                  <div className="flex items-center justify-between px-1">
                    <h4 className="font-altSans text-xs uppercase tracking-widest text-flexoki-base-500">Top Papers in this Theme</h4>
                    <div className="flex md:hidden items-center gap-2">
                      <ArrowButton
                        direction="left"
                        onClick={handlePrev}
                        disabled={totalTopics <= 1}
                        size="sm"
                      />
                      <ArrowButton
                        direction="right"
                        onClick={handleNext}
                        disabled={totalTopics <= 1}
                        size="sm"
                      />
                    </div>
                  </div>
                  <ResearchPaperCarousel papers={activePapers} section="Topic Overview" />
                </motion.div>
              </motion.article>
            </AnimatePresence>
          </div>
        </div>
      </div>
    </section>
  );
}

TopicOverview.propTypes = {
  summary: PropTypes.string.isRequired,
  totalPapers: PropTypes.number.isRequired,
  topics: PropTypes.object.isRequired,
  curationStats: PropTypes.object,
  diversityMetrics: PropTypes.object,
};
