/* eslint-disable react/no-unescaped-entities */
export default function Disclaimer() {
  return (
    <main className="flex flex-col px-4 2xl:px-0 grow w-full">
      <h1 className="font-display text-8xl mr-4 sm:mr-0 mb-8 mt-24">
        disclaimer
      </h1>
      <h2 className="font-display text-3xl text-pretty max-w-[55ch] text-base-600">
        important information about the ai-generated summaries and their usage
      </h2>
      <section className="grid grid-cols-12 mt-24 gap-12">
        <div className="col-span-12 lg:col-span-6">
          <p className="mt-4 text-base font-sans font-light text-pretty">
            I built this project in my spare time because I'm passionate about
            making academic research more accessible. While I have experience in
            this field, I'm just one person doing my best to summarize complex
            content.
          </p>
          <p className="mt-4 text-base font-sans font-light text-pretty">
            I kindly ask that you keep a few things in mind when using my little
            site:
          </p>
          <p className="mt-4 text-base font-sans font-light text-pretty">
            <strong className="font-medium">
              AI summaries are not perfect
            </strong>{" "}
            - they may miss nuances or oversimplify ideas from time to time.
            I've tried to ensure accuracy by reading through each summary, and
            skimming through papers myself, but these are generated by
            algorithms ultimately, which have limitations. I highly recommend
            checking the full research papers for a comprehensive understanding.
          </p>
          <p className="mt-4 text-base font-sans font-light text-pretty">
            <strong className="font-medium">
              Don't take the AI summaries as gospel
            </strong>{" "}
            - I'm just one well-meaning person attempting to interpret complex
            academic writing. These summaries are meant as helpful starting
            points, not authoritative replacements for the original works.
          </p>
          <p className="mt-4 text-base font-sans font-light text-pretty">
            <strong className="font-medium">
              Your feedback helps me get better
            </strong>{" "}
            - If you notice any errors or have suggestions, I'd greatly
            appreciate you reaching out. I have lots to learn and your insights
            can help me enhance this project.
          </p>
          <p className="mt-4 text-base font-sans font-light text-pretty">
            <strong className="font-medium">
              The summaries are for educational use only
            </strong>{" "}
            - While I try my best to be accurate, these are not intended for
            professional research purposes. Please consult the original papers
            for citing academic or commercial work.
          </p>
          <p className="mt-4 text-base font-sans font-light text-pretty">
            <strong className="font-medium">
              I'm doing this in my spare time with the best intentions
            </strong>{" "}
            - My goal is simply to make HCI knowledge more accessible to people
            like you. I apologize if the AI misses the mark at times. I hope you
            find some value in my little passion project!
          </p>
        </div>
      </section>
    </main>
  );
}
